baseURL = "https://ae.team"
languageCode = "en-us"
title = "Automate Everything"
themesDir = "themes"
theme = "hugo-hero-theme"
copyright = "© 2022 ae.team"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.92.0"
    
[params]
  google_analytics_id=""

  [params.logo]
    mobile = "mobile-logo.png"
    mobile_height = "72px"
    mobile_width = "72px"
    desktop = "images/ae-full.png"
    desktop_height = "100px"
    desktop_width = "100px"
    alt = "Automate Everything"

  [params.homepage_meta_tags]
    meta_description = "Automate Everything (Pty) Ltd."
    meta_og_title = "Automate Everything - DevOps as a Service"
    meta_og_type = "website"
    meta_og_url = "https://hugo-hero.netlify.app"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-hero-theme/master/images/tn.png"
    meta_og_description = "Automate Everything - DevOps products and services that scale with your business"
    meta_twitter_card = "summary"
    meta_twitter_site = "@zerostaticio"
    meta_twitter_creator = "@zerostaticio"

[[menu.main]]
    name = "Services"
    url = "/services/"
    weight = 1

[[menu.main]]
    name = "Work"
    url = "/work/"
    weight = 2

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3

[[menu.main]]
    name = "History"
    url = "/history/"
    weight = 3

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"
